import 'syncfusion-javascript/Scripts/ej/web/ej.accordion.min';
import { EJComponents } from './core';
import { EventEmitter, IterableDiffers, KeyValueDiffers, Type, ElementRef, ChangeDetectorRef } from '@angular/core';
export declare class AccordionComponent extends EJComponents<any, any> {
    el: ElementRef;
    cdRef: ChangeDetectorRef;
    private _ejIterableDiffers;
    private _ejkeyvaluediffers;
    ajaxSettings_input: any;
    allowKeyboardNavigation_input: any;
    collapseSpeed_input: any;
    collapsible_input: any;
    cssClass_input: any;
    customIcon_input: any;
    disabledItems_input: any;
    enableAnimation_input: any;
    enabled_input: any;
    enabledItems_input: any;
    enableMultipleOpen_input: any;
    enablePersistence_input: any;
    enableRTL_input: any;
    events_input: any;
    expandSpeed_input: any;
    headerSize_input: any;
    height_input: any;
    heightAdjustMode_input: any;
    htmlAttributes_input: any;
    selectedItemIndex_input: any;
    selectedItems_input: any;
    showCloseButton_input: any;
    showRoundedCorner_input: any;
    width_input: any;
    ajaxSettings_async_input: any;
    ajaxSettings_cache_input: any;
    ajaxSettings_contentType_input: any;
    ajaxSettings_data_input: any;
    ajaxSettings_dataType_input: any;
    ajaxSettings_type_input: any;
    customIcon_header_input: any;
    customIcon_selectedHeader_input: any;
    options: any;
    activate_output: EventEmitter<{}>;
    ajaxBeforeLoad_output: EventEmitter<{}>;
    ajaxError_output: EventEmitter<{}>;
    ajaxLoad_output: EventEmitter<{}>;
    ajaxSuccess_output: EventEmitter<{}>;
    beforeActivate_output: EventEmitter<{}>;
    beforeInactivate_output: EventEmitter<{}>;
    create_output: EventEmitter<{}>;
    destroy_output: EventEmitter<{}>;
    inActivate_output: EventEmitter<{}>;
    constructor(el: ElementRef, cdRef: ChangeDetectorRef, _ejIterableDiffers: IterableDiffers, _ejkeyvaluediffers: KeyValueDiffers);
}
export declare var EJ_ACCORDION_COMPONENTS: Type<any>[];
