import 'syncfusion-javascript/Scripts/ej/datavisualization/ej.bulletgraph.min';
import { EJComponents, ArrayTagElement, ComplexTagElement } from './core';
import { EventEmitter, IterableDiffers, KeyValueDiffers, Type, ElementRef, ChangeDetectorRef } from '@angular/core';
export declare class BulletGraphQualitativeRangeDirective extends ComplexTagElement {
    rangeEnd: any;
    rangeOpacity: any;
    rangeStroke: any;
    constructor(widget: EJComponents<any, any>);
}
export declare class BulletGraphQualitativeRangesDirective extends ArrayTagElement<ComplexTagElement> {
    constructor(widget: EJComponents<any, any>);
}
export declare class BulletGraphQuantitativeScaleSettingsFeatureMeasureDirective extends ComplexTagElement {
    category: any;
    comparativeMeasureValue: any;
    value: any;
    constructor(widget: EJComponents<any, any>);
}
export declare class BulletGraphQuantitativeScaleSettingsFeatureMeasuresDirective extends ArrayTagElement<ComplexTagElement> {
    constructor(widget: EJComponents<any, any>);
}
export declare class BulletGraphComponent extends EJComponents<any, any> {
    el: ElementRef;
    cdRef: ChangeDetectorRef;
    private _ejIterableDiffers;
    private _ejkeyvaluediffers;
    applyRangeStrokeToLabels_input: any;
    applyRangeStrokeToTicks_input: any;
    captionSettings_input: any;
    comparativeMeasureValue_input: any;
    enableAnimation_input: any;
    enableResizing_input: any;
    flowDirection_input: any;
    height_input: any;
    isResponsive_input: any;
    enableGroupSeparator_input: any;
    locale_input: any;
    orientation_input: any;
    qualitativeRangeSize_input: any;
    quantitativeScaleLength_input: any;
    quantitativeScaleSettings_input: any;
    theme_input: any;
    tooltipSettings_input: any;
    value_input: any;
    width_input: any;
    captionSettings_enableTrim_input: any;
    captionSettings_font_input: any;
    captionSettings_font_color_input: any;
    captionSettings_font_fontFamily_input: any;
    captionSettings_font_fontStyle_input: any;
    captionSettings_font_fontWeight_input: any;
    captionSettings_font_opacity_input: any;
    captionSettings_font_size_input: any;
    captionSettings_indicator_input: any;
    captionSettings_indicator_font_input: any;
    captionSettings_indicator_location_input: any;
    captionSettings_indicator_padding_input: any;
    captionSettings_indicator_symbol_input: any;
    captionSettings_indicator_text_input: any;
    captionSettings_indicator_textAlignment_input: any;
    captionSettings_indicator_textAnchor_input: any;
    captionSettings_indicator_textAngle_input: any;
    captionSettings_indicator_textPosition_input: any;
    captionSettings_indicator_textSpacing_input: any;
    captionSettings_indicator_visible_input: any;
    captionSettings_location_input: any;
    captionSettings_location_x_input: any;
    captionSettings_location_y_input: any;
    captionSettings_padding_input: any;
    captionSettings_subTitle_input: any;
    captionSettings_subTitle_font_input: any;
    captionSettings_subTitle_location_input: any;
    captionSettings_subTitle_padding_input: any;
    captionSettings_subTitle_text_input: any;
    captionSettings_subTitle_textAlignment_input: any;
    captionSettings_subTitle_textAnchor_input: any;
    captionSettings_subTitle_textAngle_input: any;
    captionSettings_subTitle_textPosition_input: any;
    captionSettings_text_input: any;
    captionSettings_textAlignment_input: any;
    captionSettings_textAnchor_input: any;
    captionSettings_textAngle_input: any;
    captionSettings_textPosition_input: any;
    quantitativeScaleSettings_comparativeMeasureSettings_input: any;
    quantitativeScaleSettings_comparativeMeasureSettings_stroke_input: any;
    quantitativeScaleSettings_comparativeMeasureSettings_width_input: any;
    quantitativeScaleSettings_featuredMeasureSettings_input: any;
    quantitativeScaleSettings_featuredMeasureSettings_stroke_input: any;
    quantitativeScaleSettings_featuredMeasureSettings_width_input: any;
    quantitativeScaleSettings_fields_input: any;
    quantitativeScaleSettings_fields_category_input: any;
    quantitativeScaleSettings_fields_comparativeMeasure_input: any;
    quantitativeScaleSettings_fields_dataSource_input: any;
    quantitativeScaleSettings_fields_featureMeasures_input: any;
    quantitativeScaleSettings_fields_query_input: any;
    quantitativeScaleSettings_fields_tableName_input: any;
    quantitativeScaleSettings_interval_input: any;
    quantitativeScaleSettings_labelSettings_input: any;
    quantitativeScaleSettings_labelSettings_font_input: any;
    quantitativeScaleSettings_labelSettings_labelPlacement_input: any;
    quantitativeScaleSettings_labelSettings_labelPrefix_input: any;
    quantitativeScaleSettings_labelSettings_labelSuffix_input: any;
    quantitativeScaleSettings_labelSettings_offset_input: any;
    quantitativeScaleSettings_labelSettings_position_input: any;
    quantitativeScaleSettings_labelSettings_size_input: any;
    quantitativeScaleSettings_labelSettings_stroke_input: any;
    quantitativeScaleSettings_location_input: any;
    quantitativeScaleSettings_location_x_input: any;
    quantitativeScaleSettings_location_y_input: any;
    quantitativeScaleSettings_majorTickSettings_input: any;
    quantitativeScaleSettings_majorTickSettings_size_input: any;
    quantitativeScaleSettings_majorTickSettings_stroke_input: any;
    quantitativeScaleSettings_majorTickSettings_width_input: any;
    quantitativeScaleSettings_maximum_input: any;
    quantitativeScaleSettings_minimum_input: any;
    quantitativeScaleSettings_minorTickSettings_input: any;
    quantitativeScaleSettings_minorTickSettings_size_input: any;
    quantitativeScaleSettings_minorTickSettings_stroke_input: any;
    quantitativeScaleSettings_minorTickSettings_width_input: any;
    quantitativeScaleSettings_minorTicksPerInterval_input: any;
    quantitativeScaleSettings_tickPlacement_input: any;
    quantitativeScaleSettings_tickPosition_input: any;
    tooltipSettings_captionTemplate_input: any;
    tooltipSettings_enableCaptionTooltip_input: any;
    tooltipSettings_template_input: any;
    tooltipSettings_visible_input: any;
    qualitativeRanges_input: any;
    quantitativeScaleSettings_featureMeasures_input: any;
    options: any;
    drawCaption_output: EventEmitter<{}>;
    drawCategory_output: EventEmitter<{}>;
    drawComparativeMeasureSymbol_output: EventEmitter<{}>;
    drawFeatureMeasureBar_output: EventEmitter<{}>;
    drawIndicator_output: EventEmitter<{}>;
    drawLabels_output: EventEmitter<{}>;
    drawTicks_output: EventEmitter<{}>;
    drawQualitativeRanges_output: EventEmitter<{}>;
    load_output: EventEmitter<{}>;
    Click_output: EventEmitter<{}>;
    doubleClick_output: EventEmitter<{}>;
    rightClick_output: EventEmitter<{}>;
    tag_qualitativeRanges: any;
    tag_quantitativeScaleSettings_featureMeasures: any;
    constructor(el: ElementRef, cdRef: ChangeDetectorRef, _ejIterableDiffers: IterableDiffers, _ejkeyvaluediffers: KeyValueDiffers);
}
export declare var EJ_BULLETGRAPH_COMPONENTS: Type<any>[];
