import 'syncfusion-javascript/Scripts/ej/web/ej.datepicker.min';
import { EJComponents } from './core';
import { EventEmitter, IterableDiffers, KeyValueDiffers, Type, ElementRef, ChangeDetectorRef } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
export declare const DatePickerValueAccessor: any;
export declare class DatePickerComponent extends EJComponents<any, any> implements ControlValueAccessor {
    el: ElementRef;
    cdRef: ChangeDetectorRef;
    private _ejIterableDiffers;
    private _ejkeyvaluediffers;
    allowEdit_input: any;
    allowDrillDown_input: any;
    blackoutDates_input: any;
    buttonText_input: any;
    cssClass_input: any;
    dateFormat_input: any;
    dayHeaderFormat_input: any;
    depthLevel_input: any;
    displayInline_input: any;
    enableAnimation_input: any;
    enabled_input: any;
    enablePersistence_input: any;
    enableRTL_input: any;
    enableStrictMode_input: any;
    fields_input: any;
    headerFormat_input: any;
    height_input: any;
    highlightSection_input: any;
    highlightWeekend_input: any;
    htmlAttributes_input: any;
    locale_input: any;
    maxDate_input: any;
    minDate_input: any;
    readOnly_input: any;
    showDisabledRange_input: any;
    showFooter_input: any;
    showOtherMonths_input: any;
    showPopupButton_input: any;
    showRoundedCorner_input: any;
    showTooltip_input: any;
    specialDates_input: any;
    startDay_input: any;
    startLevel_input: any;
    stepMonths_input: any;
    tooltipFormat_input: any;
    validationMessage_input: any;
    validationRules_input: any;
    value_input: any;
    watermarkText_input: any;
    weekNumber_input: any;
    width_input: any;
    fields_date_input: any;
    fields_iconClass_input: any;
    fields_tooltip_input: any;
    fields_cssClass_input: any;
    options: any;
    beforeClose_output: EventEmitter<{}>;
    beforeDateCreate_output: EventEmitter<{}>;
    beforeOpen_output: EventEmitter<{}>;
    change_output: EventEmitter<{}>;
    ejchange_output: EventEmitter<{}>;
    close_output: EventEmitter<{}>;
    create_output: EventEmitter<{}>;
    destroy_output: EventEmitter<{}>;
    focusIn_output: EventEmitter<{}>;
    focusOut_output: EventEmitter<{}>;
    navigate_output: EventEmitter<{}>;
    open_output: EventEmitter<{}>;
    select_output: EventEmitter<{}>;
    constructor(el: ElementRef, cdRef: ChangeDetectorRef, _ejIterableDiffers: IterableDiffers, _ejkeyvaluediffers: KeyValueDiffers);
    onChange: (_: any) => void;
    onTouched: () => void;
    writeValue(value: any): void;
    registerOnChange(fn: (_: any) => void): void;
    registerOnTouched(fn: () => void): void;
}
export declare var EJ_DATEPICKER_COMPONENTS: Type<any>[];
