import 'syncfusion-javascript/Scripts/ej/web/ej.dropdownlist.min';
import { EJComponents } from './core';
import { EventEmitter, IterableDiffers, KeyValueDiffers, Type, ElementRef, ChangeDetectorRef } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
export declare const DropDownListValueAccessor: any;
export declare class DropDownListComponent extends EJComponents<any, any> implements ControlValueAccessor {
    el: ElementRef;
    cdRef: ChangeDetectorRef;
    private _ejIterableDiffers;
    private _ejkeyvaluediffers;
    allowVirtualScrolling_input: any;
    cascadeTo_input: any;
    caseSensitiveSearch_input: any;
    cssClass_input: any;
    dataSource_input: any;
    delimiterChar_input: any;
    enableAnimation_input: any;
    enabled_input: any;
    enableIncrementalSearch_input: any;
    enableFilterSearch_input: any;
    enableServerFiltering_input: any;
    enablePersistence_input: any;
    enablePopupResize_input: any;
    enableRTL_input: any;
    enableSorting_input: any;
    loadOnDemand_input: any;
    fields_input: any;
    filterType_input: any;
    headerTemplate_input: any;
    height_input: any;
    htmlAttributes_input: any;
    itemsCount_input: any;
    locale_input: any;
    maxPopupHeight_input: any;
    minPopupHeight_input: any;
    maxPopupWidth_input: any;
    minPopupWidth_input: any;
    multiSelectMode_input: any;
    popupHeight_input: any;
    popupWidth_input: any;
    query_input: any;
    readOnly_input: any;
    selectedIndex_input: any;
    selectedIndices_input: any;
    showCheckbox_input: any;
    showPopupOnLoad_input: any;
    showRoundedCorner_input: any;
    sortOrder_input: any;
    targetID_input: any;
    template_input: any;
    text_input: any;
    validationMessage_input: any;
    validationRules_input: any;
    watermarkText_input: any;
    width_input: any;
    virtualScrollMode_input: any;
    fields_groupBy_input: any;
    fields_htmlAttributes_input: any;
    fields_id_input: any;
    fields_imageAttributes_input: any;
    fields_imageUrl_input: any;
    fields_selected_input: any;
    fields_spriteCssClass_input: any;
    fields_tableName_input: any;
    fields_text_input: any;
    fields_value_input: any;
    options: any;
    value_two: any;
    value_twoChange: EventEmitter<any>;
    actionBegin_output: EventEmitter<{}>;
    actionComplete_output: EventEmitter<{}>;
    actionFailure_output: EventEmitter<{}>;
    actionSuccess_output: EventEmitter<{}>;
    beforePopupHide_output: EventEmitter<{}>;
    beforePopupShown_output: EventEmitter<{}>;
    cascade_output: EventEmitter<{}>;
    change_output: EventEmitter<{}>;
    ejchange_output: EventEmitter<{}>;
    checkChange_output: EventEmitter<{}>;
    create_output: EventEmitter<{}>;
    dataBound_output: EventEmitter<{}>;
    destroy_output: EventEmitter<{}>;
    focusIn_output: EventEmitter<{}>;
    focusOut_output: EventEmitter<{}>;
    popupHide_output: EventEmitter<{}>;
    popupResize_output: EventEmitter<{}>;
    popupShown_output: EventEmitter<{}>;
    popupResizeStart_output: EventEmitter<{}>;
    popupResizeStop_output: EventEmitter<{}>;
    search_output: EventEmitter<{}>;
    select_output: EventEmitter<{}>;
    constructor(el: ElementRef, cdRef: ChangeDetectorRef, _ejIterableDiffers: IterableDiffers, _ejkeyvaluediffers: KeyValueDiffers);
    onChange: (_: any) => void;
    onTouched: () => void;
    writeValue(value: any): void;
    registerOnChange(fn: (_: any) => void): void;
    registerOnTouched(fn: () => void): void;
}
export declare var EJ_DROPDOWNLIST_COMPONENTS: Type<any>[];
