import 'syncfusion-javascript/Scripts/ej/datavisualization/ej.heatmap.min';
import { EJComponents, ArrayTagElement, ComplexTagElement } from './core';
import { EventEmitter, IterableDiffers, KeyValueDiffers, Type, ElementRef, ChangeDetectorRef } from '@angular/core';
export declare class HeatMapColorMappingDirective extends ComplexTagElement {
    color: any;
    value: any;
    label: any;
    label_bold: any;
    label_italic: any;
    label_text: any;
    label_textDecoration: any;
    label_fontSize: any;
    label_fontFamily: any;
    label_fontColor: any;
    constructor(widget: EJComponents<any, any>);
}
export declare class HeatMapColorMappingCollectionDirective extends ArrayTagElement<ComplexTagElement> {
    constructor(widget: EJComponents<any, any>);
}
export declare class HeatMapComponent extends EJComponents<any, any> {
    el: ElementRef;
    cdRef: ChangeDetectorRef;
    private _ejIterableDiffers;
    private _ejkeyvaluediffers;
    width_input: any;
    height_input: any;
    id_input: any;
    showTooltip_input: any;
    tooltipSettings_input: any;
    itemsSource_input: any;
    heatMapCell_input: any;
    isResponsive_input: any;
    enableVirtualization_input: any;
    defaultColumnStyle_input: any;
    legendCollection_input: any;
    itemsMapping_input: any;
    tooltipSettings_templateId_input: any;
    tooltipSettings_associate_input: any;
    tooltipSettings_isBalloon_input: any;
    tooltipSettings_position_input: any;
    tooltipSettings_position_target_input: any;
    tooltipSettings_position_stem_input: any;
    tooltipSettings_trigger_input: any;
    tooltipSettings_animation_input: any;
    tooltipSettings_animation_effect_input: any;
    tooltipSettings_animation_speed_input: any;
    heatMapCell_showContent_input: any;
    heatMapCell_showColor_input: any;
    defaultColumnStyle_textAlign_input: any;
    defaultColumnStyle_headerTemplateID_input: any;
    defaultColumnStyle_templateID_input: any;
    itemsMapping_columnStyle_input: any;
    itemsMapping_columnStyle_width_input: any;
    itemsMapping_columnStyle_textAlign_input: any;
    itemsMapping_columnStyle_headerTemplateID_input: any;
    itemsMapping_columnStyle_templateID_input: any;
    itemsMapping_column_input: any;
    itemsMapping_column_propertyName_input: any;
    itemsMapping_column_displayName_input: any;
    itemsMapping_row_input: any;
    itemsMapping_row_propertyName_input: any;
    itemsMapping_row_displayName_input: any;
    itemsMapping_value_input: any;
    itemsMapping_value_propertyName_input: any;
    itemsMapping_value_displayName_input: any;
    itemsMapping_headerMapping_input: any;
    itemsMapping_headerMapping_propertyName_input: any;
    itemsMapping_headerMapping_displayName_input: any;
    itemsMapping_headerMapping_columnStyle_input: any;
    itemsMapping_columnMapping_input: any;
    colorMappingCollection_input: any;
    options: any;
    cellMouseOver_output: EventEmitter<{}>;
    cellMouseEnter_output: EventEmitter<{}>;
    cellMouseLeave_output: EventEmitter<{}>;
    cellSelected_output: EventEmitter<{}>;
    tag_colorMappingCollection: any;
    constructor(el: ElementRef, cdRef: ChangeDetectorRef, _ejIterableDiffers: IterableDiffers, _ejkeyvaluediffers: KeyValueDiffers);
}
export declare var EJ_HEATMAP_COMPONENTS: Type<any>[];
