import 'syncfusion-javascript/Scripts/ej/web/ej.maskedit.min';
import { EJComponents } from './core';
import { EventEmitter, IterableDiffers, KeyValueDiffers, Type, ElementRef, ChangeDetectorRef } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
export declare const MaskEditValueAccessor: any;
export declare class MaskEditComponent extends EJComponents<any, any> implements ControlValueAccessor {
    el: ElementRef;
    cdRef: ChangeDetectorRef;
    private _ejIterableDiffers;
    private _ejkeyvaluediffers;
    cssClass_input: any;
    customCharacter_input: any;
    enabled_input: any;
    enablePersistence_input: any;
    height_input: any;
    hidePromptOnLeave_input: any;
    htmlAttributes_input: any;
    inputMode_input: any;
    locale_input: any;
    maskFormat_input: any;
    name_input: any;
    readOnly_input: any;
    showError_input: any;
    showPromptChar_input: any;
    showRoundedCorner_input: any;
    textAlign_input: any;
    validationMessage_input: any;
    validationRules_input: any;
    value_input: any;
    watermarkText_input: any;
    width_input: any;
    options: any;
    change_output: EventEmitter<{}>;
    ejchange_output: EventEmitter<{}>;
    create_output: EventEmitter<{}>;
    destroy_output: EventEmitter<{}>;
    focusIn_output: EventEmitter<{}>;
    focusOut_output: EventEmitter<{}>;
    onKeyDown_output: EventEmitter<{}>;
    keyPress_output: EventEmitter<{}>;
    keyUp_output: EventEmitter<{}>;
    mouseOut_output: EventEmitter<{}>;
    mouseOver_output: EventEmitter<{}>;
    constructor(el: ElementRef, cdRef: ChangeDetectorRef, _ejIterableDiffers: IterableDiffers, _ejkeyvaluediffers: KeyValueDiffers);
    onChange: (_: any) => void;
    onTouched: () => void;
    writeValue(value: any): void;
    registerOnChange(fn: (_: any) => void): void;
    registerOnTouched(fn: () => void): void;
}
export declare var EJ_MASKEDIT_COMPONENTS: Type<any>[];
