import 'syncfusion-javascript/Scripts/ej/web/ej.menu.min';
import { EJComponents } from './core';
import { EventEmitter, IterableDiffers, KeyValueDiffers, Type, ElementRef, ChangeDetectorRef } from '@angular/core';
export declare class MenuComponent extends EJComponents<any, any> {
    el: ElementRef;
    cdRef: ChangeDetectorRef;
    private _ejIterableDiffers;
    private _ejkeyvaluediffers;
    animationType_input: any;
    contextMenuTarget_input: any;
    container_input: any;
    cssClass_input: any;
    enableAnimation_input: any;
    enableCenterAlign_input: any;
    enabled_input: any;
    enableRTL_input: any;
    enableSeparator_input: any;
    excludeTarget_input: any;
    fields_input: any;
    height_input: any;
    htmlAttributes_input: any;
    isResponsive_input: any;
    menuType_input: any;
    openOnClick_input: any;
    orientation_input: any;
    showRootLevelArrows_input: any;
    showSubLevelArrows_input: any;
    subMenuDirection_input: any;
    titleText_input: any;
    width_input: any;
    overflowHeight_input: any;
    overflowWidth_input: any;
    fields_child_input: any;
    fields_dataSource_input: any;
    fields_htmlAttribute_input: any;
    fields_id_input: any;
    fields_imageAttribute_input: any;
    fields_imageUrl_input: any;
    fields_linkAttribute_input: any;
    fields_parentId_input: any;
    fields_query_input: any;
    fields_spriteCssClass_input: any;
    fields_tableName_input: any;
    fields_text_input: any;
    fields_url_input: any;
    options: any;
    beforeOpen_output: EventEmitter<{}>;
    click_output: EventEmitter<{}>;
    ejclick_output: EventEmitter<{}>;
    close_output: EventEmitter<{}>;
    open_output: EventEmitter<{}>;
    create_output: EventEmitter<{}>;
    destroy_output: EventEmitter<{}>;
    keydown_output: EventEmitter<{}>;
    mouseout_output: EventEmitter<{}>;
    mouseover_output: EventEmitter<{}>;
    overflowOpen_output: EventEmitter<{}>;
    overflowClose_output: EventEmitter<{}>;
    constructor(el: ElementRef, cdRef: ChangeDetectorRef, _ejIterableDiffers: IterableDiffers, _ejkeyvaluediffers: KeyValueDiffers);
}
export declare var EJ_MENU_COMPONENTS: Type<any>[];
