import 'syncfusion-javascript/Scripts/ej/web/ej.pivotchart.min';
import { EJComponents } from './core';
import { EventEmitter, IterableDiffers, KeyValueDiffers, Type, ElementRef, ChangeDetectorRef } from '@angular/core';
export declare class PivotChartComponent extends EJComponents<any, any> {
    el: ElementRef;
    cdRef: ChangeDetectorRef;
    private _ejIterableDiffers;
    private _ejkeyvaluediffers;
    analysisMode_input: any;
    cssClass_input: any;
    zooming_input: any;
    commonSeriesOptions_input: any;
    dataSource_input: any;
    customObject_input: any;
    enable3D_input: any;
    enableRTL_input: any;
    enableMultiLevelLabels_input: any;
    isResponsive_input: any;
    legend_input: any;
    locale_input: any;
    operationalMode_input: any;
    axes_input: any;
    primaryXAxis_input: any;
    primaryYAxis_input: any;
    rotation_input: any;
    enableContextMenu_input: any;
    serviceMethodSettings_input: any;
    size_input: any;
    title_input: any;
    url_input: any;
    enableXHRCredentials_input: any;
    zooming_enableScrollbar_input: any;
    commonSeriesOptions_type_input: any;
    dataSource_cube_input: any;
    dataSource_sourceInfo_input: any;
    dataSource_providerName_input: any;
    dataSource_data_input: any;
    dataSource_catalog_input: any;
    serviceMethodSettings_drillDown_input: any;
    serviceMethodSettings_exportPivotChart_input: any;
    serviceMethodSettings_initialize_input: any;
    serviceMethodSettings_paging_input: any;
    title_text_input: any;
    dataSource_columns_input: any;
    dataSource_rows_input: any;
    dataSource_values_input: any;
    dataSource_filters_input: any;
    options: any;
    load_output: EventEmitter<{}>;
    afterServiceInvoke_output: EventEmitter<{}>;
    beforeServiceInvoke_output: EventEmitter<{}>;
    beforeSeriesRender_output: EventEmitter<{}>;
    drillSuccess_output: EventEmitter<{}>;
    renderComplete_output: EventEmitter<{}>;
    renderFailure_output: EventEmitter<{}>;
    renderSuccess_output: EventEmitter<{}>;
    beforeExport_output: EventEmitter<{}>;
    constructor(el: ElementRef, cdRef: ChangeDetectorRef, _ejIterableDiffers: IterableDiffers, _ejkeyvaluediffers: KeyValueDiffers);
}
export declare var EJ_PIVOTCHART_COMPONENTS: Type<any>[];
