import 'syncfusion-javascript/Scripts/ej/web/ej.pivotgauge.min';
import { EJComponents } from './core';
import { EventEmitter, IterableDiffers, KeyValueDiffers, Type, ElementRef, ChangeDetectorRef } from '@angular/core';
export declare class PivotGaugeComponent extends EJComponents<any, any> {
    el: ElementRef;
    cdRef: ChangeDetectorRef;
    private _ejIterableDiffers;
    private _ejkeyvaluediffers;
    columnsCount_input: any;
    cssClass_input: any;
    customObject_input: any;
    dataSource_input: any;
    enableAnimation_input: any;
    enableTooltip_input: any;
    enableRTL_input: any;
    frame_input: any;
    isResponsive_input: any;
    labelFormatSettings_input: any;
    locale_input: any;
    rowsCount_input: any;
    scales_input: any;
    serviceMethodSettings_input: any;
    showHeaderLabel_input: any;
    url_input: any;
    analysisMode_input: any;
    operationalMode_input: any;
    enableXHRCredentials_input: any;
    dataSource_cube_input: any;
    dataSource_sourceInfo_input: any;
    dataSource_providerName_input: any;
    dataSource_data_input: any;
    dataSource_catalog_input: any;
    frame_frameType_input: any;
    frame_halfCircleFrameEndAngle_input: any;
    frame_halfCircleFrameStartAngle_input: any;
    labelFormatSettings_numberFormat_input: any;
    labelFormatSettings_decimalPlaces_input: any;
    labelFormatSettings_prefixText_input: any;
    labelFormatSettings_suffixText_input: any;
    serviceMethodSettings_initialize_input: any;
    dataSource_columns_input: any;
    dataSource_rows_input: any;
    dataSource_values_input: any;
    dataSource_filters_input: any;
    options: any;
    afterServiceInvoke_output: EventEmitter<{}>;
    beforeServiceInvoke_output: EventEmitter<{}>;
    beforePivotEnginePopulate_output: EventEmitter<{}>;
    load_output: EventEmitter<{}>;
    renderComplete_output: EventEmitter<{}>;
    renderFailure_output: EventEmitter<{}>;
    renderSuccess_output: EventEmitter<{}>;
    constructor(el: ElementRef, cdRef: ChangeDetectorRef, _ejIterableDiffers: IterableDiffers, _ejkeyvaluediffers: KeyValueDiffers);
}
export declare var EJ_PIVOTGAUGE_COMPONENTS: Type<any>[];
