import 'syncfusion-javascript/Scripts/ej/web/ej.pivottreemap.min';
import { EJComponents } from './core';
import { EventEmitter, IterableDiffers, KeyValueDiffers, Type, ElementRef, ChangeDetectorRef } from '@angular/core';
export declare class PivotTreeMapComponent extends EJComponents<any, any> {
    el: ElementRef;
    cdRef: ChangeDetectorRef;
    private _ejIterableDiffers;
    private _ejkeyvaluediffers;
    cssClass_input: any;
    dataSource_input: any;
    customObject_input: any;
    isResponsive_input: any;
    locale_input: any;
    operationalMode_input: any;
    serviceMethodSettings_input: any;
    url_input: any;
    enableXHRCredentials_input: any;
    dataSource_data_input: any;
    dataSource_cube_input: any;
    dataSource_sourceInfo_input: any;
    dataSource_providerName_input: any;
    dataSource_catalog_input: any;
    serviceMethodSettings_initialize_input: any;
    serviceMethodSettings_drillDown_input: any;
    dataSource_columns_input: any;
    dataSource_rows_input: any;
    dataSource_values_input: any;
    dataSource_filters_input: any;
    options: any;
    afterServiceInvoke_output: EventEmitter<{}>;
    beforeServiceInvoke_output: EventEmitter<{}>;
    load_output: EventEmitter<{}>;
    drillSuccess_output: EventEmitter<{}>;
    renderComplete_output: EventEmitter<{}>;
    renderFailure_output: EventEmitter<{}>;
    renderSuccess_output: EventEmitter<{}>;
    constructor(el: ElementRef, cdRef: ChangeDetectorRef, _ejIterableDiffers: IterableDiffers, _ejkeyvaluediffers: KeyValueDiffers);
}
export declare var EJ_PIVOTTREEMAP_COMPONENTS: Type<any>[];
