import 'syncfusion-javascript/Scripts/ej/web/ej.radiobutton.min';
import { EJComponents } from './core';
import { EventEmitter, IterableDiffers, KeyValueDiffers, Type, ElementRef, ChangeDetectorRef } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
export declare const RadioButtonValueAccessor: any;
export declare class RadioButtonComponent extends EJComponents<any, any> implements ControlValueAccessor {
    el: ElementRef;
    cdRef: ChangeDetectorRef;
    private _ejIterableDiffers;
    private _ejkeyvaluediffers;
    checked_input: any;
    cssClass_input: any;
    enabled_input: any;
    enablePersistence_input: any;
    enableRTL_input: any;
    htmlAttributes_input: any;
    id_input: any;
    idPrefix_input: any;
    name_input: any;
    size_input: any;
    text_input: any;
    validationMessage_input: any;
    validationRules_input: any;
    value_input: any;
    options: any;
    beforeChange_output: EventEmitter<{}>;
    change_output: EventEmitter<{}>;
    ejchange_output: EventEmitter<{}>;
    create_output: EventEmitter<{}>;
    destroy_output: EventEmitter<{}>;
    constructor(el: ElementRef, cdRef: ChangeDetectorRef, _ejIterableDiffers: IterableDiffers, _ejkeyvaluediffers: KeyValueDiffers);
    onChange: (_: any) => void;
    onTouched: () => void;
    writeValue(value: any): void;
    registerOnChange(fn: (_: any) => void): void;
    registerOnTouched(fn: () => void): void;
}
export declare var EJ_RADIOBUTTON_COMPONENTS: Type<any>[];
