import 'syncfusion-javascript/Scripts/ej/web/ej.rating.min';
import { EJComponents } from './core';
import { EventEmitter, IterableDiffers, KeyValueDiffers, Type, ElementRef, ChangeDetectorRef } from '@angular/core';
export declare class RatingComponent extends EJComponents<any, any> {
    el: ElementRef;
    cdRef: ChangeDetectorRef;
    private _ejIterableDiffers;
    private _ejkeyvaluediffers;
    allowReset_input: any;
    cssClass_input: any;
    enabled_input: any;
    enablePersistence_input: any;
    height_input: any;
    htmlAttributes_input: any;
    incrementStep_input: any;
    maxValue_input: any;
    minValue_input: any;
    orientation_input: any;
    precision_input: any;
    readOnly_input: any;
    shapeHeight_input: any;
    shapeWidth_input: any;
    showTooltip_input: any;
    width_input: any;
    options: any;
    value_two: any;
    value_twoChange: EventEmitter<any>;
    change_output: EventEmitter<{}>;
    ejchange_output: EventEmitter<{}>;
    click_output: EventEmitter<{}>;
    ejclick_output: EventEmitter<{}>;
    create_output: EventEmitter<{}>;
    destroy_output: EventEmitter<{}>;
    mouseout_output: EventEmitter<{}>;
    mousemove_output: EventEmitter<{}>;
    mouseover_output: EventEmitter<{}>;
    constructor(el: ElementRef, cdRef: ChangeDetectorRef, _ejIterableDiffers: IterableDiffers, _ejkeyvaluediffers: KeyValueDiffers);
}
export declare var EJ_RATING_COMPONENTS: Type<any>[];
