import 'syncfusion-javascript/Scripts/ej/web/ej.reportviewer.min';
import { EJComponents } from './core';
import { EventEmitter, IterableDiffers, KeyValueDiffers, Type, ElementRef, ChangeDetectorRef } from '@angular/core';
export declare class ReportViewerComponent extends EJComponents<any, any> {
    el: ElementRef;
    cdRef: ChangeDetectorRef;
    private _ejIterableDiffers;
    private _ejkeyvaluediffers;
    enablePageCache_input: any;
    exportSettings_input: any;
    isResponsive_input: any;
    locale_input: any;
    pageSettings_input: any;
    printMode_input: any;
    printOptions_input: any;
    processingMode_input: any;
    renderMode_input: any;
    reportPath_input: any;
    reportServerUrl_input: any;
    reportServiceUrl_input: any;
    toolbarSettings_input: any;
    zoomFactor_input: any;
    serviceAuthorizationToken_input: any;
    exportSettings_exportOptions_input: any;
    exportSettings_excelFormat_input: any;
    exportSettings_wordFormat_input: any;
    pageSettings_orientation_input: any;
    pageSettings_paperSize_input: any;
    toolbarSettings_click_input: any;
    toolbarSettings_items_input: any;
    toolbarSettings_showToolbar_input: any;
    toolbarSettings_showTooltip_input: any;
    toolbarSettings_templateId_input: any;
    dataSources_input: any;
    parameters_input: any;
    options: any;
    destroy_output: EventEmitter<{}>;
    drillThrough_output: EventEmitter<{}>;
    renderingBegin_output: EventEmitter<{}>;
    renderingComplete_output: EventEmitter<{}>;
    reportError_output: EventEmitter<{}>;
    reportExport_output: EventEmitter<{}>;
    reportLoaded_output: EventEmitter<{}>;
    showError_output: EventEmitter<{}>;
    viewReportClick_output: EventEmitter<{}>;
    ajaxBeforeLoad_output: EventEmitter<{}>;
    ajaxSuccess_output: EventEmitter<{}>;
    ajaxError_output: EventEmitter<{}>;
    toolbarRendering_output: EventEmitter<{}>;
    constructor(el: ElementRef, cdRef: ChangeDetectorRef, _ejIterableDiffers: IterableDiffers, _ejkeyvaluediffers: KeyValueDiffers);
}
export declare var EJ_REPORTVIEWER_COMPONENTS: Type<any>[];
