import 'syncfusion-javascript/Scripts/ej/web/ej.slider.min';
import { EJComponents } from './core';
import { EventEmitter, IterableDiffers, KeyValueDiffers, Type, ElementRef, ChangeDetectorRef } from '@angular/core';
export declare class SliderComponent extends EJComponents<any, any> {
    el: ElementRef;
    cdRef: ChangeDetectorRef;
    private _ejIterableDiffers;
    private _ejkeyvaluediffers;
    allowMouseWheel_input: any;
    animationSpeed_input: any;
    cssClass_input: any;
    enableAnimation_input: any;
    enabled_input: any;
    enablePersistence_input: any;
    enableRTL_input: any;
    height_input: any;
    htmlAttributes_input: any;
    incrementStep_input: any;
    largeStep_input: any;
    maxValue_input: any;
    minValue_input: any;
    orientation_input: any;
    readOnly_input: any;
    showButtons_input: any;
    showRoundedCorner_input: any;
    showScale_input: any;
    showSmallTicks_input: any;
    showTooltip_input: any;
    sliderType_input: any;
    smallStep_input: any;
    values_input: any;
    width_input: any;
    options: any;
    value_two: any;
    value_twoChange: EventEmitter<any>;
    change_output: EventEmitter<{}>;
    ejchange_output: EventEmitter<{}>;
    create_output: EventEmitter<{}>;
    destroy_output: EventEmitter<{}>;
    renderingTicks_output: EventEmitter<{}>;
    slide_output: EventEmitter<{}>;
    start_output: EventEmitter<{}>;
    stop_output: EventEmitter<{}>;
    tooltipChange_output: EventEmitter<{}>;
    constructor(el: ElementRef, cdRef: ChangeDetectorRef, _ejIterableDiffers: IterableDiffers, _ejkeyvaluediffers: KeyValueDiffers);
}
export declare var EJ_SLIDER_COMPONENTS: Type<any>[];
