import 'syncfusion-javascript/Scripts/ej/web/ej.spellcheck.min';
import { EJComponents } from './core';
import { EventEmitter, IterableDiffers, KeyValueDiffers, Type, ElementRef, ChangeDetectorRef } from '@angular/core';
export declare class SpellCheckComponent extends EJComponents<any, any> {
    el: ElementRef;
    cdRef: ChangeDetectorRef;
    private _ejIterableDiffers;
    private _ejkeyvaluediffers;
    dictionarySettings_input: any;
    misspellWordCss_input: any;
    locale_input: any;
    maxSuggestionCount_input: any;
    ignoreWords_input: any;
    contextMenuSettings_input: any;
    ignoreSettings_input: any;
    isResponsive_input: any;
    enableValidateOnType_input: any;
    controlsToValidate_input: any;
    enableAsync_input: any;
    ajaxRequestType_input: any;
    ajaxDataType_input: any;
    dictionarySettings_dictionaryUrl_input: any;
    dictionarySettings_customDictionaryUrl_input: any;
    contextMenuSettings_enable_input: any;
    contextMenuSettings_menuItems_input: any;
    ignoreSettings_ignoreAlphaNumericWords_input: any;
    ignoreSettings_ignoreEmailAddress_input: any;
    ignoreSettings_ignoreMixedCaseWords_input: any;
    ignoreSettings_ignoreUpperCase_input: any;
    ignoreSettings_ignoreUrl_input: any;
    ignoreSettings_ignoreFileNames_input: any;
    options: any;
    actionSuccess_output: EventEmitter<{}>;
    actionBegin_output: EventEmitter<{}>;
    actionFailure_output: EventEmitter<{}>;
    start_output: EventEmitter<{}>;
    complete_output: EventEmitter<{}>;
    contextOpen_output: EventEmitter<{}>;
    contextClick_output: EventEmitter<{}>;
    dialogBeforeOpen_output: EventEmitter<{}>;
    dialogOpen_output: EventEmitter<{}>;
    dialogClose_output: EventEmitter<{}>;
    validating_output: EventEmitter<{}>;
    targetUpdating_output: EventEmitter<{}>;
    constructor(el: ElementRef, cdRef: ChangeDetectorRef, _ejIterableDiffers: IterableDiffers, _ejkeyvaluediffers: KeyValueDiffers);
}
export declare var EJ_SPELLCHECK_COMPONENTS: Type<any>[];
