import 'syncfusion-javascript/Scripts/ej/web/ej.splitbutton.min';
import { EJComponents } from './core';
import { EventEmitter, IterableDiffers, KeyValueDiffers, Type, ElementRef, ChangeDetectorRef } from '@angular/core';
export declare class SplitButtonComponent extends EJComponents<any, any> {
    el: ElementRef;
    cdRef: ChangeDetectorRef;
    private _ejIterableDiffers;
    private _ejkeyvaluediffers;
    arrowPosition_input: any;
    buttonMode_input: any;
    contentType_input: any;
    cssClass_input: any;
    enabled_input: any;
    enableRTL_input: any;
    height_input: any;
    htmlAttributes_input: any;
    imagePosition_input: any;
    prefixIcon_input: any;
    showRoundedCorner_input: any;
    size_input: any;
    suffixIcon_input: any;
    targetID_input: any;
    target_input: any;
    text_input: any;
    width_input: any;
    options: any;
    beforeOpen_output: EventEmitter<{}>;
    click_output: EventEmitter<{}>;
    ejclick_output: EventEmitter<{}>;
    close_output: EventEmitter<{}>;
    create_output: EventEmitter<{}>;
    destroy_output: EventEmitter<{}>;
    itemMouseOut_output: EventEmitter<{}>;
    itemMouseOver_output: EventEmitter<{}>;
    itemSelected_output: EventEmitter<{}>;
    open_output: EventEmitter<{}>;
    constructor(el: ElementRef, cdRef: ChangeDetectorRef, _ejIterableDiffers: IterableDiffers, _ejkeyvaluediffers: KeyValueDiffers);
}
export declare var EJ_SPLITBUTTON_COMPONENTS: Type<any>[];
