import 'syncfusion-javascript/Scripts/ej/web/ej.tab.min';
import { EJComponents } from './core';
import { EventEmitter, IterableDiffers, KeyValueDiffers, Type, ElementRef, ChangeDetectorRef } from '@angular/core';
export declare class TabComponent extends EJComponents<any, any> {
    el: ElementRef;
    cdRef: ChangeDetectorRef;
    private _ejIterableDiffers;
    private _ejkeyvaluediffers;
    ajaxSettings_input: any;
    allowKeyboardNavigation_input: any;
    collapsible_input: any;
    cssClass_input: any;
    disabledItemIndex_input: any;
    enableAnimation_input: any;
    enabled_input: any;
    enabledItemIndex_input: any;
    enablePersistence_input: any;
    enableRTL_input: any;
    enableTabScroll_input: any;
    events_input: any;
    headerPosition_input: any;
    headerSize_input: any;
    height_input: any;
    heightAdjustMode_input: any;
    hiddenItemIndex_input: any;
    htmlAttributes_input: any;
    idPrefix_input: any;
    showCloseButton_input: any;
    showReloadIcon_input: any;
    showRoundedCorner_input: any;
    width_input: any;
    ajaxSettings_async_input: any;
    ajaxSettings_cache_input: any;
    ajaxSettings_contentType_input: any;
    ajaxSettings_data_input: any;
    ajaxSettings_dataType_input: any;
    ajaxSettings_type_input: any;
    options: any;
    selectedItemIndex_two: any;
    selectedItemIndex_twoChange: EventEmitter<any>;
    itemActive_output: EventEmitter<{}>;
    ajaxBeforeLoad_output: EventEmitter<{}>;
    ajaxError_output: EventEmitter<{}>;
    ajaxLoad_output: EventEmitter<{}>;
    ajaxSuccess_output: EventEmitter<{}>;
    beforeActive_output: EventEmitter<{}>;
    beforeItemRemove_output: EventEmitter<{}>;
    create_output: EventEmitter<{}>;
    destroy_output: EventEmitter<{}>;
    itemAdd_output: EventEmitter<{}>;
    itemRemove_output: EventEmitter<{}>;
    constructor(el: ElementRef, cdRef: ChangeDetectorRef, _ejIterableDiffers: IterableDiffers, _ejkeyvaluediffers: KeyValueDiffers);
}
export declare var EJ_TAB_COMPONENTS: Type<any>[];
