import 'syncfusion-javascript/Scripts/ej/web/ej.toolbar.min';
import { EJComponents } from './core';
import { EventEmitter, IterableDiffers, KeyValueDiffers, Type, ElementRef, ChangeDetectorRef } from '@angular/core';
export declare class ToolbarComponent extends EJComponents<any, any> {
    el: ElementRef;
    cdRef: ChangeDetectorRef;
    private _ejIterableDiffers;
    private _ejkeyvaluediffers;
    cssClass_input: any;
    dataSource_input: any;
    disabledItemIndices_input: any;
    enabled_input: any;
    enabledItemIndices_input: any;
    enableRTL_input: any;
    enableSeparator_input: any;
    fields_input: any;
    height_input: any;
    htmlAttributes_input: any;
    hide_input: any;
    isResponsive_input: any;
    Items_input: any;
    orientation_input: any;
    query_input: any;
    responsiveType_input: any;
    showRoundedCorner_input: any;
    width_input: any;
    fields_group_input: any;
    fields_htmlAttributes_input: any;
    fields_id_input: any;
    fields_imageAttributes_input: any;
    fields_imageUrl_input: any;
    fields_spriteCssClass_input: any;
    fields_text_input: any;
    fields_tooltipText_input: any;
    fields_template_input: any;
    Items_group_input: any;
    Items_htmlAttributes_input: any;
    Items_id_input: any;
    Items_imageAttributes_input: any;
    Items_imageUrl_input: any;
    Items_spriteCssClass_input: any;
    Items_text_input: any;
    Items_tooltipText_input: any;
    Items_template_input: any;
    options: any;
    click_output: EventEmitter<{}>;
    ejclick_output: EventEmitter<{}>;
    create_output: EventEmitter<{}>;
    focusOut_output: EventEmitter<{}>;
    destroy_output: EventEmitter<{}>;
    itemHover_output: EventEmitter<{}>;
    itemLeave_output: EventEmitter<{}>;
    overflowOpen_output: EventEmitter<{}>;
    overflowClose_output: EventEmitter<{}>;
    constructor(el: ElementRef, cdRef: ChangeDetectorRef, _ejIterableDiffers: IterableDiffers, _ejkeyvaluediffers: KeyValueDiffers);
}
export declare var EJ_TOOLBAR_COMPONENTS: Type<any>[];
