import 'syncfusion-javascript/Scripts/ej/web/ej.tooltip.min';
import { EJComponents } from './core';
import { EventEmitter, IterableDiffers, KeyValueDiffers, Type, ElementRef, ChangeDetectorRef } from '@angular/core';
export declare class TooltipComponent extends EJComponents<any, any> {
    el: ElementRef;
    cdRef: ChangeDetectorRef;
    private _ejIterableDiffers;
    private _ejkeyvaluediffers;
    allowKeyboardNavigation_input: any;
    animation_input: any;
    associate_input: any;
    autoCloseTimeout_input: any;
    closeMode_input: any;
    collision_input: any;
    containment_input: any;
    content_input: any;
    cssClass_input: any;
    enabled_input: any;
    enableRTL_input: any;
    height_input: any;
    isBalloon_input: any;
    position_input: any;
    showRoundedCorner_input: any;
    showShadow_input: any;
    target_input: any;
    tip_input: any;
    title_input: any;
    trigger_input: any;
    width_input: any;
    animation_effect_input: any;
    animation_speed_input: any;
    position_target_input: any;
    position_target_horizontal_input: any;
    position_target_vertical_input: any;
    position_stem_input: any;
    position_stem_horizontal_input: any;
    position_stem_vertical_input: any;
    tip_size_input: any;
    tip_size_width_input: any;
    tip_size_height_input: any;
    tip_adjust_input: any;
    tip_adjust_xValue_input: any;
    tip_adjust_yValue_input: any;
    options: any;
    beforeClose_output: EventEmitter<{}>;
    beforeOpen_output: EventEmitter<{}>;
    click_output: EventEmitter<{}>;
    ejclick_output: EventEmitter<{}>;
    close_output: EventEmitter<{}>;
    create_output: EventEmitter<{}>;
    destroy_output: EventEmitter<{}>;
    hover_output: EventEmitter<{}>;
    open_output: EventEmitter<{}>;
    tracking_output: EventEmitter<{}>;
    constructor(el: ElementRef, cdRef: ChangeDetectorRef, _ejIterableDiffers: IterableDiffers, _ejkeyvaluediffers: KeyValueDiffers);
}
export declare var EJ_TOOLTIP_COMPONENTS: Type<any>[];
