import 'syncfusion-javascript/Scripts/ej/datavisualization/ej.treemap.min';
import { EJComponents, ArrayTagElement, ComplexTagElement } from './core';
import { EventEmitter, IterableDiffers, KeyValueDiffers, Type, ElementRef, ChangeDetectorRef } from '@angular/core';
export declare class TreeMapLevelDirective extends ComplexTagElement {
    groupBackground: any;
    groupBorderColor: any;
    groupBorderThickness: any;
    groupGap: any;
    groupPadding: any;
    groupPath: any;
    headerHeight: any;
    headerTemplate: any;
    headerVisibilityMode: any;
    labelPosition: any;
    textOverflow: any;
    labelTemplate: any;
    labelVisibilityMode: any;
    showHeader: any;
    showLabels: any;
    constructor(widget: EJComponents<any, any>);
}
export declare class TreeMapLevelsDirective extends ArrayTagElement<ComplexTagElement> {
    constructor(widget: EJComponents<any, any>);
}
export declare class TreeMapRangeColorDirective extends ComplexTagElement {
    color: any;
    gradientColors: any;
    from: any;
    legendLabel: any;
    to: any;
    constructor(widget: EJComponents<any, any>);
}
export declare class TreeMapRangeColorMappingDirective extends ArrayTagElement<ComplexTagElement> {
    constructor(widget: EJComponents<any, any>);
}
export declare class TreeMapComponent extends EJComponents<any, any> {
    el: ElementRef;
    cdRef: ChangeDetectorRef;
    private _ejIterableDiffers;
    private _ejkeyvaluediffers;
    borderBrush_input: any;
    borderThickness_input: any;
    uniColorMapping_input: any;
    desaturationColorMapping_input: any;
    paletteColorMapping_input: any;
    colorValuePath_input: any;
    colorPath_input: any;
    dockPosition_input: any;
    drillDownHeaderColor_input: any;
    drillDownSelectionColor_input: any;
    isHierarchicalDatasource_input: any;
    header_input: any;
    enableDrillDown_input: any;
    drillDownValue_input: any;
    drillDownLevel_input: any;
    isResponsive_input: any;
    enableResize_input: any;
    draggingOnSelection_input: any;
    draggingGroupOnSelection_input: any;
    legendSettings_input: any;
    highlightBorderBrush_input: any;
    highlightBorderThickness_input: any;
    highlightGroupBorderBrush_input: any;
    highlightGroupBorderThickness_input: any;
    highlightGroupOnSelection_input: any;
    highlightOnSelection_input: any;
    itemsLayoutMode_input: any;
    enableGroupSeparator_input: any;
    locale_input: any;
    leafItemSettings_input: any;
    selectionMode_input: any;
    groupSelectionMode_input: any;
    showLegend_input: any;
    enableGradient_input: any;
    showTooltip_input: any;
    tooltipTemplate_input: any;
    treeMapItems_input: any;
    uniColorMapping_color_input: any;
    desaturationColorMapping_to_input: any;
    desaturationColorMapping_color_input: any;
    desaturationColorMapping_from_input: any;
    desaturationColorMapping_rangeMaximum_input: any;
    desaturationColorMapping_rangeMinimum_input: any;
    paletteColorMapping_colors_input: any;
    legendSettings_height_input: any;
    legendSettings_width_input: any;
    legendSettings_iconHeight_input: any;
    legendSettings_iconWidth_input: any;
    legendSettings_template_input: any;
    legendSettings_mode_input: any;
    legendSettings_title_input: any;
    legendSettings_leftLabel_input: any;
    legendSettings_rightLabel_input: any;
    legendSettings_dockPosition_input: any;
    legendSettings_alignment_input: any;
    legendSettings_columnCount_input: any;
    leafItemSettings_borderBrush_input: any;
    leafItemSettings_borderThickness_input: any;
    leafItemSettings_gap_input: any;
    leafItemSettings_itemTemplate_input: any;
    leafItemSettings_labelPath_input: any;
    leafItemSettings_labelPosition_input: any;
    leafItemSettings_textOverflow_input: any;
    leafItemSettings_labelVisibilityMode_input: any;
    leafItemSettings_showLabels_input: any;
    groupColorMapping_input: any;
    rangeColorMapping_input: any;
    levels_input: any;
    options: any;
    dataSource_two: any;
    dataSource_twoChange: EventEmitter<any>;
    weightValuePath_two: any;
    weightValuePath_twoChange: EventEmitter<any>;
    treeMapItemSelected_output: EventEmitter<{}>;
    itemRendering_output: EventEmitter<{}>;
    legendItemRendering_output: EventEmitter<{}>;
    drillStarted_output: EventEmitter<{}>;
    drillDownItemSelected_output: EventEmitter<{}>;
    headerTemplateRendering_output: EventEmitter<{}>;
    refreshed_output: EventEmitter<{}>;
    treeMapGroupSelected_output: EventEmitter<{}>;
    Click_output: EventEmitter<{}>;
    doubleClick_output: EventEmitter<{}>;
    rightClick_output: EventEmitter<{}>;
    tag_levels: any;
    tag_rangeColorMapping: any;
    constructor(el: ElementRef, cdRef: ChangeDetectorRef, _ejIterableDiffers: IterableDiffers, _ejkeyvaluediffers: KeyValueDiffers);
}
export declare var EJ_TREEMAP_COMPONENTS: Type<any>[];
