import { ModuleWithProviders } from "@angular/core";
export * from './ej/grid.component';
export { GridGroupcaptionTemplateDirective } from './ej/gridtemplates/grid.groupcaption.template';
export { GridEditTemplateDirective } from './ej/gridtemplates/grid.edit.template';
export { GridDetailsTemplateDirective } from './ej/gridtemplates/grid.details.template';
export { GridSummaryTemplateDirective } from './ej/gridtemplates/grid.summary.template';
export { GridRowTemplateDirective } from './ej/gridtemplates/grid.row.template';
export * from './ej/chart.component';
export * from './ej/diagram.component';
export * from './ej/overview.component';
export * from './ej/sunburstchart.component';
export * from './ej/symbolpalette.component';
export * from './ej/heatmap.component';
export * from './ej/heatmaplegend.component';
export * from './ej/rangenavigator.component';
export * from './ej/sparkline.component';
export * from './ej/bulletgraph.component';
export * from './ej/circulargauge.component';
export * from './ej/lineargauge.component';
export * from './ej/map.component';
export * from './ej/treemap.component';
export * from './ej/digitalgauge.component';
export * from './ej/spreadsheet.component';
export * from './ej/datepicker.component';
export * from './ej/gantt.component';
export * from './ej/treegrid.component';
export { TreeGridHeaderTemplateDirective } from './ej/treegridtemplates/treegrid.header.template';
export * from './ej/colorpicker.component';
export * from './ej/dialog.component';
export * from './ej/scroller.component';
export * from './ej/barcode.component';
export * from './ej/pdfviewer.component';
export * from './ej/numerictextbox.component';
export * from './ej/currencytextbox.component';
export * from './ej/percentagetextbox.component';
export * from './ej/timepicker.component';
export * from './ej/toolbar.component';
export * from './ej/menu.component';
export * from './ej/autocomplete.component';
export * from './ej/maskedit.component';
export * from './ej/treeview.component';
export * from './ej/schedule.component';
export * from './ej/kanban.component';
export * from './ej/ribbon.component';
export * from './ej/pivotgrid.component';
export * from './ej/pivotclient.component';
export * from './ej/pivotchart.component';
export * from './ej/pivotschemadesigner.component';
export * from './ej/pivotpager.component';
export * from './ej/pivottreemap.component';
export * from './ej/pivotgauge.component';
export * from './ej/rating.component';
export * from './ej/listbox.component';
export * from './ej/listview.component';
export * from './ej/rotator.component';
export * from './ej/rte.component';
export * from './ej/dropdownlist.component';
export * from './ej/combobox.component';
export * from './ej/radialmenu.component';
export * from './ej/signature.component';
export * from './ej/radialslider.component';
export * from './ej/tile.component';
export * from './ej/navigationdrawer.component';
export * from './ej/accordion.component';
export * from './ej/tab.component';
export * from './ej/checkbox.component';
export * from './ej/radiobutton.component';
export * from './ej/togglebutton.component';
export * from './ej/splitbutton.component';
export * from './ej/datetimepicker.component';
export * from './ej/daterangepicker.component';
export * from './ej/progressbar.component';
export * from './ej/tagcloud.component';
export * from './ej/button.component';
export * from './ej/groupbutton.component';
export * from './ej/tooltip.component';
export * from './ej/slider.component';
export * from './ej/fileexplorer.component';
export * from './ej/reportviewer.component';
export * from './ej/reportdesigner.component';
export * from './ej/splitter.component';
export * from './ej/uploadbox.component';
export * from './ej/waitingpopup.component';
export * from './ej/spellcheck.component';
export * from './ej/core';
export { EJTemplateDirective } from './ej/template';
export declare class EJAngular2Module {
    static forRoot(): ModuleWithProviders;
}
